### ISSUE TITLE
Child component not overriding default InputField 

### ISSUE THREAD

**Issue by abeering** [gpietro/react-numpad#1]
I'm having a hard time getting `NumPad` to render my `InputField` override. 

```jsx
<NumPad.Number onChange={(value) => { console.log('value', value)}}>
  <input className="form-control input-lg" type="number" />
</NumPad.Number>
```

And yet: 

<img width="647" alt="screen shot 2018-01-22 at 2 28 53 pm" src="https://user-images.githubusercontent.com/166016/35247815-a379c18a-ff80-11e7-90c9-cff1a2fff71c.png">

I've tried a number of basic inputs, using different `type`, with/without `className`, etc. 

Everything I've seen in the code leads me to believe that it should work, I just can't get it to go.

https://github.com/gpietro/react-numpad/blob/master/lib/components/NumPad.js#L44

I'm assuming I'm just missing something .. but I can't figure it out.  Any ideas would be appreciated. 

Thanks.

**Comment by gpietro** [comment]
Hi @abeering, it should actually work. Here is a [demo](https://codesandbox.io/s/o4lvln4k3q).
Anyway I did some changes (use v. 1.2.1), before it didn't work with dateFormat and displayRule props because were assigned to the dom element.
Make sure to have the latest version of React in your app (16.2.0).
I'll close this issue for now.
